import { createApiClient } from '@ajoti/shared'
const client=createApiClient({baseUrl:import.meta.env.VITE_API_BASE_URL??'',storagePrefix:'',sessionExpiredRedirect:'/'})
const {authRequest}=client
export type TargetSavingsMember={id:string;userId:string;user:{firstName:string;lastName:string};savedAmountKobo:string;targetAmountKobo:string;progressPercent:number;status:string;maturityDestination:'SELF'|'ORGANISER'}
export type TargetSavingsPlan={id:string;ownerId:string;type:'INDIVIDUAL'|'GROUP';name:string;description?:string|null;targetAmountKobo:string;contributionAmountKobo:string;frequency:'DAILY'|'WEEKLY'|'MONTHLY';currency:string;startDate:string;maturityDate:string;status:string;isPublic:boolean;inviteToken?:string;memberCount:number;totalSavedKobo:string;groupTargetAmountKobo:string;myMembership:TargetSavingsMember|null;members:TargetSavingsMember[]}
const unwrap=<T>(r:{data?:T}|T):T=>('data'in (r as object)&&(r as {data?:T}).data?(r as {data:T}).data:r as T)
export async function getMyTargetSavings(){const r=await authRequest<{data?:TargetSavingsPlan[]}|TargetSavingsPlan[]>('/api/target-savings/mine',{method:'GET'});return Array.isArray(r)?r:(r.data??[])}
export async function getPublicTargetSavings(){const r=await authRequest<{data?:TargetSavingsPlan[]}|TargetSavingsPlan[]>('/api/target-savings/public',{method:'GET'});return Array.isArray(r)?r:(r.data??[])}
export async function createTargetSavings(payload:{type:'INDIVIDUAL'|'GROUP';name:string;description?:string;targetAmountKobo:string;contributionAmountKobo:string;frequency:'DAILY'|'WEEKLY'|'MONTHLY';startDate:string;maturityDate:string;isPublic?:boolean}){return unwrap(await authRequest<{data?:TargetSavingsPlan}|TargetSavingsPlan>('/api/target-savings',{method:'POST',body:JSON.stringify(payload)}))}
export async function joinTargetSavings(id:string,inviteToken?:string){return authRequest(`/api/target-savings/${id}/join`,{method:'POST',body:JSON.stringify({inviteToken})})}
export async function contributeTargetSavings(id:string,amountKobo:string){return authRequest(`/api/target-savings/${id}/contributions`,{method:'POST',body:JSON.stringify({amountKobo})})}
export async function setTargetMaturityDestination(id:string,destination:'SELF'|'ORGANISER',transactionPin?:string){return authRequest(`/api/target-savings/${id}/maturity-destination`,{method:'PATCH',body:JSON.stringify({destination,transactionPin})})}
